### ISSUE TITLE
AssertionError: expected <Accordion /> to have a 'props' prop

### ISSUE THREAD

**Issue by zitsen** [hallister/semantic-react#109]
Currently I have decided to learn React.In the case of my previous Semantic-UI experience,
I'm trying to contribute to this project, begining with the `Statistic` view implementation.

But when I try to start with `npm test`, it just failed as:
```
FAILED TESTS:
  Accordion
    ✖ Passes props as props property
      Node.js (linux; U; rv:v6.2.1)
    AssertionError: expected <Accordion /> to have a 'props' prop     
         
         HTML:
         
         <div data-test="test" class="ui accordion"></div>
        at Context.<anonymous> （webpack:///src/components/modules/accordion/__tests__/accordion-test.jsx:47:32)
```

I'm sure using the latest master.

I've little experience with `karma` and `React`, anyone help?

**Comment by asvetliakov** [comment]
Hello
Accordion was slightly changed in recent commits, and looks like we forgot to update tests.
You can fix test byself - now props are being passed directly rather than through props property:

change line 47 to in accordion/__tests__/accordion-test.jsx:
```jsx
expect(wrapper).to.have.prop('data-test', 'test');
```
