### ISSUE TITLE
Sluggish Transition (react-motion-ui-pack)

### ISSUE THREAD

**Issue by loris** [hallister/semantic-react#110]
I find that currently the way react-motion-ui-pack is used (ie, when opening/closing Select/Dropdown/Modal/etc.) is pretty sluggish and slow compared to how vanilla Semantic UI behaves.
I tried to set custom `enterAnimation`, `leaveAnimation` but the `react-motion` API makes it quite difficult to match the same transition feeling. Besides that, there looks like there is a bug when setting a `leaveAnimation` not sure in which deps the issue is:

```js
      <Select
        active={active}
        onSelectChange={this.onSelectChange}
        onClick={this.onClick}
        onRequestClose={this.onRequestClose}
        enterAnimation={{
          height: {
            val: 'auto',
            stiffness: 500,
            damping: 30,
          },
        }}
        leaveAnimation={{
          height: {
            val: 0,
            stiffness: 500,
            damping: 30,
          },
        }}
      >
```

![](https://dl.dropboxusercontent.com/spa/tqch4axi0t55dpk/6eyrmzsm.png)

In the end, what i'm just trying to achieve is a dropdown menu which opens and closes more quickly...

**Comment by asvetliakov** [comment]
I noticed it too and few other issues with current animation state, will try to rework soon:
1) Going to drop react-motion-ui-pack in favor of just react-motion. This will have a consequence though and we'll lose ability to pass enterAnimation/leaveAnimation for a while.
2) Animation optimization - going to make sure that animation rerender will not rerender whole component (affects accordion very noticeable)
We can go with CSS animation route (i.e. CSSTransitionGroup), i don't like it much though. Let me know your opinion.

For now, did you try to pass ```precision``` to spring configs?

**Comment by loris** [comment]
I don’t know much about animation/transition in React yet, will take a look at it and get back to you.
For the time being, my workaround is to disable transition completely 😄 
```
<Select
  enterAnimation={{}}
  leaveAnimation={{}}
/>
```

**Comment by asvetliakov** [comment]
I think i managed it, by replacing react-motion-ui-pack with just react-motion and increasing precision to 10 in spring configuration. Now dropdown is more fast and doesn't have height stickness problem at low values when rolling in.
As consequence, menu now is mounted from beginning with display: none
Another problem is that all items in menu are being re-rendered on each style rerender. This may become slow for large menus or complex menu items. Will try to manage this

**Comment by asvetliakov** [comment]
@loris 
Can you try latest version from master?
Changes:
1) Select and DropdownMenu now uses react-motion directly
2) enterAnimation/leaveAnimation now accept spring config object, i.e. {stiffness, damping, precision}. Default values are 700, 50, 40 and it seems pretty fast and nice.
3) Optmized rerendering for dropdown menu & select. (in dropdownmenu child items were rendered 100 times per item during animation, now 0, select only rerenders when sliding out/it  (so only 2))
4) Select now handles overflow more correctly and applies scroll if needed (if select has more than 6 or 8 items (if has scrolling option - funny semantic behavior))
5) Few changes in MenuItem - it's now calling onClick with provided menuValue by self instead binding handler in parent component. Should affect you only if you're using own components as MenuItem-s (likely you're not)

**Comment by loris** [comment]
@asvetliakov Great work! looks good to me. The defaults are cool.

- Would be great to allow disabling transitions (for instance `<Select enterAnimation=false leaveAnimation=false />` would use `react-motion` without `spring`)
- I suppose you intend to make the same improvements to other Transition uses? (popup, modal, etc.)

**Comment by asvetliakov** [comment]
1) You can pass something like it { stiffness: 5000, precision: 5000, damping: 500 } to hide transition now, but yes, easy disabling is something that we need
2) Yes

**Comment by asvetliakov** [comment]
@loris 
I completed transition to vanilla react-motion and changed animation again.
Here is example how you can apply custom animations to component (or custom spring configuration):
https://github.com/hallister/semantic-react/blob/master/src/components/modules/modal/examples/customAnimation.jsx

**Comment by herenow** [comment]
The animations are also/still "sluggish" here, specifically the dimmer animation (and other animations that use "fade").

Looking at the inspector, it seems that our dimmer animation is done via JS, with a timer and manipulating the opacity, while semantic-ui does it via css transition and fallbacks to jQuery's fadeTo if css transitions are not available.

I wonder if we couldn't do the same, use css transitions and only set the `animation-duration` via js, and fallback to react-motion if not available.

@asvetliakov you said you didn't like the "CSS animation route", is there any particular reason :)?
