### ISSUE TITLE
Fix Unknown Prop error in React 15.2

### ISSUE THREAD

**Issue by loris** [hallister/semantic-react#118]
Since 15.2, React now displays errors (in dev setup) when unknown props are passed to HTML elements. `semantic-react` is responsible for many of them, for instance, in Menu:

![](https://dl.dropboxusercontent.com/spa/tqch4axi0t55dpk/s_afps4l.png)

Apparently, some more props (like `onMenuItemClick`) need to be removed using destructuring to avoid passing them down to `div`, `a`, `span`, etc elements. I can push some PR for the elements i'm using in my project.

**Comment by asvetliakov** [comment]
Yes, i just noticed it too.
I'm doing some work now for replacing animation to vanilla react-motion on left components (modal, accordion, search). Will look into react 15.2 issue after, but PR welcome 👍

**Comment by soosap** [comment]
Hi, i am still having this issue with **Card**
![image](https://cloud.githubusercontent.com/assets/7187705/16981653/d570bb20-4e6b-11e6-9c7a-9b3424d89733.png)

Seems like `component` it is missing in here:
`let { centered, col, color, doubling, defaultClasses, fluid, link, ...other } = this.props;`

**Comment by asvetliakov** [comment]
Thanks for reporting, will fix soon
