### ISSUE TITLE
Css don't show

### ISSUE THREAD

**Issue by EQuimper** [hallister/semantic-react#123]
Hey, I try your packages and see the component work inside the console but no style are show.

**Comment by asvetliakov** [comment]
Did you include/link semantic-css ?

**Comment by EQuimper** [comment]
No how I do this ?

**Comment by EQuimper** [comment]
You mean from the semantic website ?

**Comment by asvetliakov** [comment]
You need to include something like this https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css to your html page.
Another option is to use webpack and install semantic-ui or semantic-ui-less (requires custom build process) and require it somewhere in your app.

**Comment by EQuimper** [comment]
Good perfect sorry for this. Thank you a lot for this awesome package. 

P.S typo MenuItem in the import

**Comment by asvetliakov** [comment]
Sorry for unclear instructions! Perhaps i should add it to readme.

**Comment by EQuimper** [comment]
Last thing how you ref a value from a input ? That's was working before I put the Input component

**Comment by asvetliakov** [comment]
The Input is being wrapped to div (by semantic) so you need to use controlled component here or onChange/onBlur prop.

**Comment by EQuimper** [comment]
Ok so what you do if you have a lot of input ? For get the value from onBlur I need to use `e.target.value` no ?

**Comment by asvetliakov** [comment]
i'd make separate component if you want to access to input:
```jsx

class MyInput extends React.Component {
  state = {
    input: ""
  };
 
  onChange = (evt) => {
    this.setState({ input: evt.target.value });
  }

  getValue() {
     return this.state.input;
  }
 
  render() {
    return<Input {...this.props} onChange={this.onChange} value={this.state.input}/>
 }
}

// consumer code

<MyInput ref={ref => this.input = ref}/>

ref.getValue();
```

**Comment by EQuimper** [comment]
Thank you again wow, last thing I think I have find a little bug with the Menu. I try to use it with React-Router and Link. If I put the Link around the MenuItem I can't render the Link and if I put it inside the MenuItem I can only render the Link if I click the text not the full item.

**Comment by asvetliakov** [comment]
Yes because Link is different component which renders ```<a>```

You can have 2 options:
first:

```
<MenuItem component={Link} to="/lalala"/>
```

second
```
import {browserHistory} from "react-router";

<Menu onMenuChange={(val) => { if (val) browserHistory.push("/lalala"); }>
``` 
for controlled menu (with menuValue)

or ```<MenuItem onClick={() => browserHistory.push(...)}/>```
or similar for uncontrolled menu
react-router also provides different ways to call push (context, props, etc...)

**Comment by EQuimper** [comment]
Thank again I use the browserHistory good idea
