### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by EQuimper** [hallister/semantic-react#127]
I got a problem with the Rating component. I find a way to change the state by hard coding but the ui don't change. What is my problem here :(

```js
import React, { Component } from 'react';
import { Icon, Rating } from 'semantic-react';

export class InputRating extends Component {
  constructor() {
    super();
    this.state = {
      value: 0,
    };
    this.handleRating = this.handleRating.bind(this);
  }
  handleRating(e) {
    this.setState({
      value: e.target.value,
    });
    this.star.state.value = this.state.value;
  }
  getValue() {
    return this.state.value;
  }
  render() {
    return (
      <div className="rating-container">
        <Rating star max="5" size="massive" ref={ref => this.star = ref} initialValue="0" />
        <br />
        <div>
          <input
            type="range"
            onChange={this.handleRating}
            value={this.state.value}
            min="0"
            max="5"
            step="1"
          />
          <br />
          {this.state.value}
        </div>
      </div>
    );
  }
}
\
```

**Comment by asvetliakov** [comment]
Thanks for reporting! I'll probably make it controlled then

**Comment by EQuimper** [comment]
And I get some problem making the feed with event etc. I see in the console the class is there but nothing show. So I finish by just doing it manually with classname

**Comment by asvetliakov** [comment]
Feed & events are old components (most components were reworked from original hallister's version) and are not even tested. Feel free to send PR for them

**Comment by EQuimper** [comment]
Good yes I can make some stuff ;) Thank you again I really like your work

**Comment by asvetliakov** [comment]
@EQuimper 
I reworked Rating completely, please update to 0.8.0
Example: http://hallister.github.io/semantic-react/#!/Rating

Also i removed star and heart props, now there is a type: "default" | "star" | "heart" instead

**Comment by asvetliakov** [comment]
Feel free to reopen if you have any issues

**Comment by EQuimper** [comment]
So now If I want to update the star with a slide can I use value inside the Rating ?

**Comment by asvetliakov** [comment]
Yes, it's fully controlled now.

**Comment by EQuimper** [comment]
Perfect thank you
