### ISSUE TITLE
Form -> Field -> Input doesn't render same as Semantic

### ISSUE THREAD

**Issue by TimNZ** [hallister/semantic-react#131]
Using your Form example.

Your Input is rendered in a &lt;div class="ui input&gt; which is breaking Semantic.css for input where state = 'error' and type != 'input'

Yours
```
<div class="field">
<label>Email</label>
<div class="ui input"><input type="password" value="" placeholder="Password"></div>
</div>
```

Should be:
```
<div class="field error">
            <label>Password</label>
            <input type="password" name="password">
</div>
```

**Comment by s4ge** [comment]
http://hallister.github.io/semantic-react/#Form

Here it renders correctly. Can you post the code which produces your issue?

**Comment by TimNZ** [comment]
Thanks.  Don't know what I was doing before but it works as expected.  Likely setting properties on wrong element.
