### ISSUE TITLE
animation?

### ISSUE THREAD

**Issue by hyusetiawan** [hallister/semantic-react#136]
There are quite a bit of issues opened about animation (react-motion, etc), but I am not able to see how to use it?
for example, I checked http://react.semantic-ui.com/modules/dropdown and no mention of animation, perhaps I am missing something?

**Comment by asvetliakov** [comment]
The link is from other semantic react library (official one) and they don't support animations yet.

Here for our: http://hallister.github.io/semantic-react
I switched animations to CSS semantic-ui transitions recently, so old animation issues are not relevant anymore.
Check the Modal/Popup examples how to specify animation transitions

**Comment by hyusetiawan** [comment]
ah excuse my mistake, and thank you for the prompt response
