### ISSUE TITLE
[Breadcrumb]: Implement component.

### ISSUE THREAD

**Issue by hallister** [hallister/semantic-react#25]
Since breadcrumbs and a router go hand in hand, it's probably better to either port [react-breadcrumbs](https://github.com/svenanders/react-breadcrumbs) or just use it and pass classes by hand.

**Comment by loris** [comment]
I added some props to [react-breadcrumbs](https://github.com/svenanders/react-breadcrumbs) (see [PR](https://github.com/svenanders/react-breadcrumbs/pull/44)) a few weeks ago to make it compatible with Semantic UI markup. Now you can use it this way:

```js
import React from 'react';
import { Icon } from 'semantic-react';
import Breadcrumbs from 'react-breadcrumbs';

const Breadcrumb = props =>
  <Breadcrumbs
    {...props}
    separator={<Icon name="right angle divider" />}
    wrapperClass="ui breadcrumb"
    itemClass="section"
    activeItemClass="active"
  />;

export default Breadcrumb;
```
