### ISSUE TITLE
Animate, Animations pbs

### ISSUE THREAD

**Issue by xmehaut** [hallister/semantic-react#29]
Hello,
I'm currently trying to port your code in typescript/react to have a native typescript ui library... I've already coded many elements without problems (while trying to use typescript features like typing, generics, class hierarchy, ...)... but once I've started with Animate, Animations, Dimmer, Modal, ..., I've encounter big problems to make thinks working... 

My question is : is the code on github currently works for the latter components? I see for instance than Animations use the component Transition which doesn't exists in react... 

best regards
xavier

**Comment by aphofstede** [comment]
@hallister stated he [built his own animation library](https://github.com/hallister/semantic-react/issues/3#issuecomment-149221514)
afaics he's using react-addons-transition-group for Transition.

**Comment by hallister** [comment]
Yep, and the react-addons-transition-group has some bugs, so it will have to be brought over at somepoint. But basically you need React with addons for now.

**Comment by asvetliakov** [comment]
I particular replaced your Animation with react-motion-ui-pack (https://github.com/souporserious/react-motion-ui-pack/), only Modal with Popup left (but i'm going to rework them to use new RenderToLayer). warning messages were gone and select labels are now animated :smile_cat: 
Are you interested or still preferring to stick with your current animation solution?

**Comment by asvetliakov** [comment]
Moving to react-motion and react-motion-ui-pack now
