### ISSUE TITLE
[Components]: Animations issues

### ISSUE THREAD

**Issue by hallister** [hallister/semantic-react#3]
There are a couple of issues with ReactTransitionGroup that are causing some problems.

Issues
* Has to wrap all animated components in a HTML tag, breaking CSS for Semantic.
* RTG consumes refs for all animated components.
* When using custom components ReactTransitionGroup doesn't cosume the component prop.

Results
* Labels in select dropdowns can't animate.
* Anything that animates leave/enter will get a warning for invalid `component` prop.
* We can't use a `Animations` for Dropdown because it will consume the search boxes ref.

**Comment by newsiberian** [comment]
Hi, did you looked at the [react-motion](https://github.com/chenglou/react-motion) for animation purpose? The project looks very promise. If not, then I suggest you to check them examples and especially video on GH page.

**Comment by hallister** [comment]
I actually really like react-motion, but the goal of this project is a 1:1 translation of Semantic UI's jquery to react which is counter to react-motions "let me animate this for you", which is why I implemented my own animation library. I can definitely see a future where we either replace or allow react-motion as an option.
