### ISSUE TITLE
Can you add more people who can merge commits?

### ISSUE THREAD

**Issue by Asgator** [hallister/semantic-react#41]
Can you add more people who can merge commits?

**Comment by hallister** [comment]
Absolutely, @asvetliakov and @aphofstede have been doing a lot of work lately, are either of you interested? I have zero time atm for reviewing PR's.

**Comment by asvetliakov** [comment]
@hallister Yes, you can me add as collaborator, if you're accepting the direction which i'm moving on:
1) using react-motion & react-motion-ui-pack instead your Animation lib
2) Adding some controlled elements (for ex. Menu which manages current active item and provides onMenuChange onMenuItemClick callbacks)
3) Doc overhaul. Current works great for simple elements but not for statefull ones (need to write code for documenting popup for example)

**Comment by hallister** [comment]
I agree on all accounts. The current animation lib was a stop gap while I waited for something better to come along and I'd say react-motion-ui-pack fits the bill. The docs were effectively the same thing, just a stop gap measure. Managing active items needs a better solution than what I have so I'm all for it. Will add you momentarily.

**Comment by aphofstede** [comment]
@hallister, @asvetliakov is probably your guy. I could help with documentation, examples and generally making the lib play nice. The way it looks now I'll be adding examples and missing properties wherever I find them missing whilst using the components in my own projects.

**Comment by Asgator** [comment]
@hallister, @asvetliakov,  My project need all the components ```semantic``` and I can also help in the development of.

**Comment by asvetliakov** [comment]
Great, Thanks :+1:
Any suggestions for good doc library? I found few: https://github.com/pocotan001/react-styleguide-generator and https://www.npmjs.com/package/react-styleguidist (this is markdown one)
@Asgator 
My project using many components too. Thanks god, many of them had already been implemented.

**Comment by hallister** [comment]
https://www.npmjs.com/package/react-styleguidist appears to be more active, and looks really clean. That would be my vote, but I imagine either will be a little easier than the custom "thing" I made.

**Comment by asvetliakov** [comment]
react-styleguidist works flawlessly:
[Image](http://imgur.com/SAqHSo8)

**Comment by aphofstede** [comment]
Looks good @asvetliakov, do we need to re-do existing examples for it?

**Comment by asvetliakov** [comment]
@aphofstede 
Yes, but it's easier now, just write the full jsx in markdown

**Comment by asvetliakov** [comment]
Just merged PR with react-styleguidist and other stuff (notably dimmer, popup and select/dropdown), for any interested: welcome :smile:

**Comment by aphofstede** [comment]
Could you point me to an example of the react-styleguidist way of making examples? Is it already in master?

**Comment by asvetliakov** [comment]
@aphofstede see src/components/modules/dropdown/select.examples.md for example

**Comment by asvetliakov** [comment]
Looks like i'm going to abandon react-styleguidist and use different tool, or modify previous hallister's work to allow write examples in markdown / jsx files.
Though react-styleguidist is simple to use and it's working good for simple tasks, there are few problems:
1. We need semantify standard styleguidist components to make it look good
2. Single-page is very slooooow when there are many components. Especially for height animating (check the accordion example for ex.)
3. CodeMirror (live examples) if fun tool, but it becomes very slow when there are many components
4. Again, markdown live examples breaks styling for modals/dimmer (looks like zindex problem or so)
Don't want to fix all these stuff
