### ISSUE TITLE
[Discussion]: Inline styling and Radium

### ISSUE THREAD

**Issue by asvetliakov** [hallister/semantic-react#42]
Since inline styles in React is very popular, what do you guys think about direct Radium (http://stack.formidable.com/radium/) support? This will help folks (and me too) to do inlining styling.
Currently to use Radium need to write something like this:
```javascript
import {Button} from "semantic-react";
const RadiumButton = Radium(Button);
```
this works but breaks tests for shallow rendering (you can't use enzyme.find(Button) for example) - for workaround need to create big wrapper for semantic components and re-export them (and use them in  tests too).
Another advanced technique, css-modules doesn't work flawlessly with semantic - in our project we've ended with pretty much :(global) selectors to override some semantic default styles, so we're switching to inline styling now 
Pros
- Allows folks to use radium stuff without any efforts and tricks
- Works transparently, doesn't break anything else
- Easy to implement, just add decorator to components

Cons
- Another dependency, +50kb non-gzipped minified with radium deps

**Comment by Asgator** [comment]
Hmm, maybe need create new project  ``` semantic-react-radium ```. Where  ```radium``` expands ```semantic-react```. Because not everyone needs ```Radium``` project.

**Comment by asvetliakov** [comment]
@Asgator 
> Where radium expands semantic-react

* You can pass array of styles including radium selectors for free. <Button style=[{style.one, style.first}]>test</Button>
* 50kb is not pretty much of dependency
* If some time in future semantic-react will manage styling byself (see earlier discussions), this could be a base to start


May be separate entry point and peer dependency ?

**Comment by asvetliakov** [comment]
I added separate entry point "semantic-react/radium" and removed package.json dependency on radium
