### ISSUE TITLE
[Discussion/Components] Maximize controlled components, minimize internal state

### ISSUE THREAD

**Issue by SunspotsEU** [hallister/semantic-react#44]
While there might be use for both controlled and uncontrolled components, I think it's important that controlled components are completely controlled.
To allow both side by side, possibly allow both value and defaultValue, or similar analogies.
https://facebook.github.io/react/docs/forms.html

For a controlled component, view-state might as well be uncontrolled (ex. show/hide/selected) but value/active state should always be controlled.

Example: The default semantic menu items has two states: `selected` and `active`
`active` is the currently active item, such as the current page, the "value" of select, etc.
`active` should always reflect the input props, it should never be changed without explicitly passing a new prop. This is the point of controlled components - an input should always reflect data from up top. If I click an item in the menu; a selection event happens, but the parent node should evaluate the selection and choose whether to pass in the new active value to the menu.

`selected` is the item currently highlighted by other means (default selection on search, selected by keyboard input (arrow keys))
`selected` state may be controlled by the component, as it does not reflect the form input, but rather visual UI state.

This has implications when dropdowns and selects are built on top of it.
A controlled select should never change value by itself, the onChange/onSelect event should emit the selected value, but it shouldn't change it's own value, the value should only change when the select receives new props.

Initializing state by props and then mutating it internally in a component is an anti-pattern.

I'm going to take a look at what I can do, but I'd be glad to get your input.

**Comment by asvetliakov** [comment]
Menu in the lib could be both controlled and uncontrolled
DropdownMenu and Select uses controlled menu (i.e. passing active prop/with selected class name byself to given menuitem)
Select is very complex component since it could mix 3 variations (multiple, search, ui select/ui button). And i'm not sure if we can it make as outside controlled component, each state could have different logic. However i agree that this could be useful

**Comment by asvetliakov** [comment]
Hm, if i'll make only controlled select i can remove almost all logic and leave it to user. Also it will allow to easy move search stuff to other component, for example Select and SearchSelect

**Comment by SunspotsEU** [comment]
Exactly!
I'll try to come up with a pull request.

I've previously used https://github.com/JedWatson/react-select/ and it has gone through some similar issues and changes. But I think it's too focused on searchable items and inputting a data structure instead of just passing children.

**Comment by asvetliakov** [comment]
Not needed PR to avoid duplicating work, i'll make necessary changes in few days

**Comment by SunspotsEU** [comment]
I already started fiddling with it at https://github.com/SunspotsEU/semantic-react
There are some other features I want to look at as well, so I think I'll continue on.
I'm fine with duplicating work, I've got lots of time on my hands.

**Comment by asvetliakov** [comment]
As part of changes, menu is fully controlled now, doing dropdown

**Comment by asvetliakov** [comment]
With #52 merging you should able to fully control select. See docs for example. There is a problem with animating labels though, but this is minor

**Comment by SunspotsEU** [comment]
The setState in styleguidist seems to redraw the entire component, I think that's why animations break.

**Comment by asvetliakov** [comment]
yeah, looks like because CodeMirror. Then we can ignore that for now. Also there is a minor problem too with focus is always being placed on the beginning of the search box. Not sure if it's because styleguidist too :smile:

**Comment by asvetliakov** [comment]
If wrap example into react class then everything works as expected
