### ISSUE TITLE
Input label- and icon-props

### ISSUE THREAD

**Issue by aphofstede** [hallister/semantic-react#49]
The Input component has `labeled` and `icon` props; which are actually not used, but set automatically to true if you add a `Label` or `Icon` component as a child.
In the property definition (`propTypes` field) though, they are defined as being `bool` or `string`, which implies different possibilities for interacting with the component. 

Which interaction / paradigm do we want here? Do we want to encourage a certain way of setting up your hierarchy?

I see a couple of options:

- No properties exposed. The `Input` component looks at its children and does some magic based on what it finds. (We should remove the props from `propTypes` then)
- Bool properties exposed and enforced. e.g. If you set `labeled` to true, you **must** put a `<Label/>` in the children.
- String props exposed. e.g. `<Input icon="cloud"/>` would automagically become `<Input><Icon name="cloud"/></Input>`
- Label, Icon (and Button) defined through props. Input should accept all props that these subcomponents do, and you can just set them on `<Input />`. (Note: You'll get clashes for some, like `name`)
- A combination of the above / allow multiple ways of setting things up.

Note: In a [recent PR](https://github.com/hallister/semantic-react/pull/45), support for a Button child was added; I chose the first option for that case..
We might want to think about making whatever gets decided a more recurring pattern in the component usage.

**Comment by asvetliakov** [comment]
I'd go for combining 3 & 4 together. If i want labeledbutton i want to write <LabeledButton label="label" icon="cloud" /> and nothing else.
We should consider also to allow to override these generated components in such case, for example <LabeledButton labelComponent={MySuperLabel}/>
The 1) needed only for few components which should have some additional markup/classes depends of childs.

**Comment by tomitrescak** [comment]
Yes, just got caught up in it trying to add the icon via "icon='cloud'" and does not work yet ;) will be awesome though! Good for testing as well!

**Comment by asvetliakov** [comment]
Some stuff had been done in https://github.com/hallister/semantic-react/pull/71 and https://github.com/hallister/semantic-react/pull/70
