### ISSUE TITLE
[Semantic UI]: Significant use of free-floating text nodes causes issues with React.

### ISSUE THREAD

**Issue by hallister** [hallister/semantic-react#6]
Semantic uses a lot of free floating text nodes. [It's causing issues](https://github.com/Semantic-Org/Semantic-UI/issues/2918) with a number of React components. Notably, the statistic view is not possible with React and Semantic, without using `dangerouslySetInnerHTML`.

**Comment by asvetliakov** [comment]
Looks like it shouldn't cause any problem with upcoming react 15.0.0
https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html
