### ISSUE TITLE
How to integrate in a webpack based project?

### ISSUE THREAD

**Issue by purezen** [hallister/semantic-react#68]
I have been looking to integrate Semantic-UI in my webpack-based React project and need some help in integrating the library with the same.

Also, how does this differ from the original Semantic-UI project. It can too be integrated with a React app, right? Is it to do with not using jQuery manipulations?

**Comment by Asgator** [comment]
Add in package.json
```
dependencies: {
     .... ///
    "semantic-react": "git+https://github.com/hallister/semantic-react.git",
}
```
next

```
npm i semantic-react
```

in project 
```
import { Segment } from 'semantic-react/lib/elements';
```

**Comment by asvetliakov** [comment]
Better:
```javascript
import { Segment } from 'semantic-react';
```

**Comment by loris** [comment]
Adding `semantic-react` to my webpack vendor minified bundle made it grow from 201kb (which already included `react`, `react-dom` and `react-router`, both in their latest version, v15, etc) to 570kb. How can I assure dependencies are not bundled twice?

**Comment by asvetliakov** [comment]
V15 react is not supported yet. The react-motion and react-motion-ui-pack declares react-v14 in their dependencies, thus you'll get them installed and bundled along with your v15

**Comment by asvetliakov** [comment]
Ok, new version react-motion-ui-pack was released 12 hours ago with react v15 support, i'll update soon

**Comment by loris** [comment]
Cool, was doing some debugging inside my webpack bundle, and I do confirm that the culprit was `react-motion-ui-pack`, thanks a lot!

**Comment by asvetliakov** [comment]
https://github.com/hallister/semantic-react/pull/81 Should allow to use react v15. Make sure that npm deleted react stuff from node_modules/react-motion-ui-pack/node_modules/
