### ISSUE TITLE
Make use of babel-plugin-transform-react-remove-prop-types

### ISSUE THREAD

**Issue by loris** [hallister/semantic-react#82]
[transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) removes useless propTypes object from production build.
Could help with reducing the final bundle size. Just tried and the `lib` folder went from `1.3M` to `1.1M`

**Comment by asvetliakov** [comment]
Good point :+1: , but leaving it for pre-release, don't have any time now. PR welcome though

**Comment by loris** [comment]
Next step would to be to have the same modularity as `lodash`. Meaning that `import { Button } from 'semantic-react'` should only bundle the button and related code.

**Comment by asvetliakov** [comment]
You can include only particular element even now:
```
import Button from 'semantic-react/lib/button/button'
```
but yeah, it could be improved for something like this
```
import Button from 'semantic-react/lib/Button`
```

**Comment by loris** [comment]
Cool, works great this way:
`import Button from 'semantic-react/lib/elements/button/button';`
Indeed some shortcuts would be great :)
