### ISSUE TITLE
Error running with the latest clone

### ISSUE THREAD

**Issue by geohuz** [hallister/semantic-react#99]
Hi all, I just cloned the code and try to run npm install and styleguide-server, and now get the following error:

```
hr is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`. Check the render method of MDReactComponent.
```

**Comment by asvetliakov** [comment]
This is should be just warning, isn't it? I doubt that this prevents styleguide from working. Anyway looks like i need to update deps :smile_cat: 

I'm very busy last weeks, expect some kind of delay for fixing, probably until these weekends or so.

**Comment by asvetliakov** [comment]
You can also try to update project deps (i'm using npm-check-updates for that) and see if issue is resolved, send PR in this case

**Comment by nkrambo** [comment]
I'm experiencing the same issue with the latest clone. I updated any outdated packages but unfortunately still getting the same error message.

**Comment by asvetliakov** [comment]
Should be fixed now, error comes from styleguide-server which uses pretty old Markdown component.
